# Generated by Django 3.0.6 on 2020-05-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('user_id', models.CharField(max_length=20, verbose_name='이름')),
                ('password', models.CharField(max_length=60, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100, verbose_name='이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
