# Generated by Django 3.0.6 on 2020-05-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='폰번호'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(max_length=20, verbose_name='유저아이디'),
        ),
    ]
