# Generated by Django 3.0.6 on 2020-05-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200507_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(max_length=250, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='account',
            name='post',
            field=models.CharField(max_length=250, null=True, verbose_name='주소'),
        ),
    ]
