# Generated by Django 3.0.4 on 2020-05-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
