# Generated by Django 3.0.4 on 2020-05-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_is_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
