# Generated by Django 3.0.3 on 2020-05-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200522_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='kakao_id',
            field=models.IntegerField(null=True),
        ),
    ]
