# Generated by Django 3.0.6 on 2020-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200510_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.AddField(
            model_name='product',
            name='item_price',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='price_red',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='price_strike',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
